version: '3'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

#  admin-service:
#    image: admin_service
#    build:
#      context: ./services/admin_service
#      dockerfile: Dockerfile
#    tty: true
#    networks:
#      - static-network
#    depends_on:
#      - consul-server

#  ad-service:
#    image: ad_service
#    build:
#      context: ./services/ad_service
#      dockerfile: Dockerfile
#    tty: true
#    networks:
#      - static-network
#    depends_on:
#      - consul-server

#  renting-service:
#    image: renting_service
#    build:
#      context: ./services/renting_service
#      dockerfile: Dockerfile
#    tty: true
#    networks:
#      - static-network
#    depends_on:
#      - consul-server

#  authentication-service:
#    image: authentication_service
#    build:
#      context: ./services/authentication_service
#      dockerfile: Dockerfile
#    tty: true
#    networks:
#      - static-network
#    depends_on:
#      - consul-server

#  gps-service:
#     image: gps_service
#     build:
#       context: ./services/gps_service
#       dockerfile: Dockerfile
#     tty: true
#     networks:
#       - static-network
#     depends_on:
#       - consul-server

#  security-service:
#     image: security_service
#     build:
#       context: ./services/security_service
#       dockerfile: Dockerfile
#     tty: true
#     networks:
#       - static-network
#     depends_on:
#       - consul-server

  agentski-bekend:
     image: agentski_bekend
     build:
       context: ./agentski_bekend
       dockerfile: Dockerfile
     tty: true
     networks:
       - static-network
     depends_on:
       - consul-server
  agentska-baza:
    restart: always
    image: mysql
#	build: 
#	  context: ./agentska_baza
#	  dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: agentski_bekend
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
#    healthcheck:
#      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
#      interval: 2s
#      timeout: 20s
#      retries: 10

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
