spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka}
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:db}?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

server:
  port: 8761
#  ssl:
#    enabled: true
#    key-store: classpath:gateway.dc1.rent-a-car.keystore.p12
#    key-store-password: 739476603727
#    trust-store: classpath:rent-a-car.truststore.p12
#    trust-store-password: 739476603727
#    key-alias: gateway.dc1.rent-a-car
#    client-auth: need



eureka:
  instance:
    hostname: ${springboot.app.name:eureka}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
